import os
import re
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE # Import for styles
import google.generativeai as genai
import sys
import subprocess
from docx.shared import RGBColor
from MainJarvis_TaskExecution import speak

# Define a light blue color in RGB
LIGHT_BLUE = RGBColor(79,129,189) # RGB for LightBlue
HEADING_COLOR = RGBColor(55,96,146)



try:
    GENIMNI_API_KEY = os.getenv("GEMINI_API_1") # Replace with your Gemini API key
    genai.configure(api_key=GENIMNI_API_KEY)
    model = genai.GenerativeModel("gemini-1.5-pro")
    # Simple test to check if the API key works and model is accessible
    # model.generate_content("Ping", request_options={"timeout": 10})
except Exception as e:
    print(f"❌ Failed to connect to Gemini API or load model. Check your API key and network connection: {e}")
    exit(1)



# ====== Prompt Builder ======
# Modified prompt for detailed Code and Output sections, structured Theory with bullets, small Conclusion, and user requirements
def build_prompt(topic, include_code, requirements):
    return f"""
You are acting as a diligent engineering student writing a high-quality, detailed, and professional assignment report. Your task is to generate content for an assignment based on the given topic and requirements.

The assignment report should have the following sections and demonstrate significant effort and understanding, typical of a student who has thoroughly completed the work. Ensure the overall tone is professional and appropriate for an engineering assignment.

Title: [Provide a concise, clear title for the assignment. This is mandatory.]
Aim: [State the objective of the assignment in one or two sentences.]
Theory: [Provide detailed and comprehensive theoretical background, explanations, and relevant concepts related to the topic. **Structure the Theory section into distinct logical sub-parts or paragraphs with clear topic sentences.** Within these sub-parts, **use bullet points (preceded by * or -) to list key details, features, steps, or examples** where appropriate. Explain *why* things work in depth.]

{'''
Code: [Present the complete, functional, and **very detailed** code required for the assignment. The code should be well-structured, include **extensive comments** explaining logical blocks and important lines, and if applicable, demonstrate multiple functions or classes or cover various aspects of the topic. Aim for code that clearly reflects a thorough implementation and significant work.]
Output: [Show **very detailed and comprehensive** output generated by running the 'Code' section. Include output for **multiple scenarios or test cases** that fully demonstrate the code's functionality, handle potential edge cases, and illustrate the results of the code execution extensively. Format it clearly as terminal or program output.]
''' if include_code else ''}

Conclusion: [Provide a **brief and concise** summary of the work done and key findings. Discuss what was learned or implemented in a few sentences. Focus on the technical outcomes and execution. **Do NOT include the LO Mapping in this section; it will be added separately.**]

👉 Specific Assignment Requirements/Constraints:
{requirements if requirements else "No specific requirements provided."}

👉 Tone and Style:
- Write in a clear, technical, and formal tone, reflecting a strong grasp of the subject matter and project execution.
- Use appropriate technical terms accurately.
- Ensure explanations in the Theory, Code (via comments), and Output sections are thorough and demonstrate a deep understanding.
- Structure the conclusion to provide a concise technical summary.

👉 Formatting Notes (for content generation):
- Provide plain, clean text for all sections. No HTML.
- **You may use * or - at the start of a line for list items within the Theory section.**
- Assume the final document uses Times New Roman font, size 12pt, with 1.5 line spacing for main content. Code/Output will use a monospace font, size 11pt, 1.0 spacing.

Topic: {topic}
""".strip()

# ====== Add Paragraph Helper ======
def add_paragraph(doc, text, size=12, bold=False, align_center=False, font="Times New Roman", spacing=1.5, color=None):
    para = doc.add_paragraph()
    run = para.add_run(text)
    run.font.size = Pt(size)
    run.font.name = font
    run.bold = bold
    if color:
        run.font.color.rgb = color
    para_format = para.paragraph_format
    para_format.line_spacing = spacing
    if align_center:
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return para

# ====== Markdown-like List Item Helper ======
def add_list_item(doc, text, style='List Bullet', size=12, font="Times New Roman", spacing=1.5):
    """Adds a paragraph formatted as a list bullet."""
    p = doc.add_paragraph(style=style)
    run = p.add_run(text.lstrip('* ').lstrip('- ')) # Remove common markdown list markers
    run.font.size = Pt(size)
    run.font.name = font
    para_format = p.paragraph_format
    para_format.line_spacing = spacing
    return p


# ====== Assignment Parser ======
def parse_assignment_response(text, include_code):
    sections = {
        "title": "",
        "aim": "",
        "theory": "",
        "code": "",
        "output": "",
        "conclusion": ""
    }

    pattern = r"(Title|Aim|Theory|Code|Output|Conclusion):"
    parts = re.split(pattern, text, flags=re.IGNORECASE)

    for i in range(1, len(parts), 2):
        key = parts[i].strip().lower()
        value = parts[i+1].strip()
        if key in sections:
            sections[key] = value

    # Ensure code and output are cleared if not requested, even if AI includes them
    if not include_code:
        sections["code"] = ""
        sections["output"] = ""

    return sections

def generate_assignment(topic: str, include_code: bool, requirements: str, lo_mapping_text: str, assignment_number: str, model = model, build_prompt = build_prompt, parse_assignment_response=parse_assignment_response, add_paragraph=add_paragraph, add_list_item=add_list_item, LIGHT_BLUE=LIGHT_BLUE, HEADING_COLOR=HEADING_COLOR):
    """
    Function to generate an engineering assignment and save it as a .docx file.
    
    Args:
    - topic (str): Topic of the assignment.
    - include_code (bool): Whether to include code and output.
    - requirements (str): Additional requirements or constraints for the assignment.
    - lo_mapping_text (str): The LO Mapping text for the conclusion.
    - assignment_number (str): The assignment number.
    - model: Model object to generate content.
    - build_prompt: Function to build the prompt for the model.
    - parse_assignment_response: Function to parse the response.
    - add_paragraph: Function to add paragraphs to the document.
    - add_list_item: Function to add list items to the document.
    - LIGHT_BLUE: Color for headings.
    - HEADING_COLOR: Color for main headings.
    """
    
    if not topic:
        print("❌ Please enter a valid topic.")
        return

    speak(f"Generating the assignment: {topic} in a bit.")

    try:
        # Generate content from the model
        response = model.generate_content(build_prompt(topic, include_code, requirements), request_options={"timeout": 90})
        text = response.text.strip()

        data = parse_assignment_response(text, include_code)

        # Create DOCX file
        doc = Document()

        # Apply default style formatting (Times New Roman, 12pt, 1.5 spacing)
        styles = doc.styles
        style_normal = styles['Normal']
        font = style_normal.font
        font.name = 'Times New Roman'
        font.size = Pt(12)
        para_format = style_normal.paragraph_format
        para_format.line_spacing = 1.5
        para_format.space_before = Pt(0)
        para_format.space_after = Pt(0)

        # Main Heading (Assignment - n)
        main_heading_part1 = f"Assignment - {assignment_number}"
        add_paragraph(doc, main_heading_part1, size=18, bold=True, align_center=True, spacing=1.0, color=HEADING_COLOR)

        # Assignment Title (Below Assignment - n)
        assignment_title_text = f"({data['title']})"
        add_paragraph(doc, assignment_title_text, size=16, bold=True, align_center=True, spacing=1.0, color=HEADING_COLOR)

        # Aim - Light Blue Heading
        add_paragraph(doc, "\nAim:", bold=True, spacing=1.0, color=LIGHT_BLUE)
        add_paragraph(doc, data["aim"], spacing=1.5)

        # Theory - Light Blue Heading, Structured with possible Bullet Points
        add_paragraph(doc, "\nTheory:", bold=True, spacing=1.0, color=LIGHT_BLUE)
        theory_lines = data["theory"].split('\n') # Split by single newline to process potential lists
        for line in theory_lines:
            line = line.strip()
            if not line:
                doc.add_paragraph('', style='Normal') # Add blank line for paragraph separation
                continue
            if line.startswith('* ') or line.startswith('- '):
                add_list_item(doc, line, style='List Bullet', size=12, font="Times New Roman", spacing=1.5)
            else:
                add_paragraph(doc, line, spacing=1.5)

        # Code Section (if applicable)
        if include_code and data["code"]:
            add_paragraph(doc, "\nCode:", bold=True, spacing=1.0, color=LIGHT_BLUE)
            for line in data["code"].splitlines():
                add_paragraph(doc, line, size=11, spacing=1.0, font="Consolas")

        # Output Section (if applicable)
        if include_code and data["output"]:
            add_paragraph(doc, "\nOutput:", bold=True, spacing=1.0, color=LIGHT_BLUE)
            for line in data["output"].splitlines():
                add_paragraph(doc, line, size=11, spacing=1.0, font="Consolas")

        # Conclusion Section
        add_paragraph(doc, "\nConclusion:", bold=True, spacing=1.0, color=LIGHT_BLUE)
        for paragraph_text in data["conclusion"].split('\n\n'):
            add_paragraph(doc, paragraph_text.strip(), spacing=1.5)

        # LO Mapping Text (if provided)
        if lo_mapping_text:
            add_paragraph(doc, "\nLO Mapping:", bold=True, spacing=1.0, color=LIGHT_BLUE)
            add_paragraph(doc, lo_mapping_text.strip(), spacing=1.5)

        # Save DOCX
        safe_topic = "".join(c for c in topic if c.isalnum() or c in (' ', '_', '-')).rstrip()
        safe_topic = safe_topic.replace(' ', '_')
        if not safe_topic: safe_topic = "Assignment"
        filename = f"Assignment_{safe_topic}.docx"

        doc.save(filename)
        
        print(f"Assignment saved as: {filename}")
        speak("Assignment Saved Succesfully.")

        # Attempt to open the saved file
        speak("Attempting to open the document...")
        # speak(f"Attempting to open '{filename}'...")
        try:
            if os.name == "nt":  # Windows
                os.startfile(filename)
            # elif sys.platform == "darwin":  # macOS
            #     subprocess.run(["open", filename], check=True)
            # elif os.name == "posix":  # Linux/Unix
            #     if os.system("command -v xdg-open > /dev/null") == 0:
            #         subprocess.run(["xdg-open", filename], check=True)
            #     else:
            #         print("ℹ️ 'xdg-open' command not found. Could not automatically open the document.")
            else:
                speak("Could not automatically open the document. Please open it manually.")
        except Exception as e:
            # speak(f"⚠️ Error: {e}")
            speak(f"An unexpected error occurred while trying to open the document: {e}")
    except Exception as e:
        print(f"❌ An error occurred: {e}")
        speak("Sorry Sir.Failed to generate or save assignment. Please try again later.")

# ====== MAIN ======
if __name__ == "__main__":
    print("📚 JARVIS Assignment Creator\n")

    topic = input("🧠 Enter your assignment topic: ").strip()
    if not topic:
        print("❌ Please enter a valid topic.")
        exit()

    code_based = input("💡 Does this assignment include coding and output? (yes/no): ").strip().lower()
    include_code = code_based in ['yes', 'y']

    # Get more details from the user
    requirements = input("📝 Enter any specific requirements or constraints for the assignment (optional): ").strip()
    lo_mapping_text = input("🎓 Enter the LO Mapping text exactly as it should appear in the conclusion: ").strip()
    if not lo_mapping_text:
        print("⚠️ Warning: No LO Mapping text provided by the user.")

    assignment_number = input("🔢 Enter the assignment number (e.g., 1, 2): ").strip()
    if not assignment_number:
         print("⚠️ Warning: No assignment number provided. Using 'n'.")
         assignment_number = "n"
    elif not assignment_number.isdigit():
         print("⚠️ Warning: Invalid assignment number. Using 'n'.")
         assignment_number = "n"


    print("\n⏳ Generating assignment content using Gemini...")

    try:
        # Adjusted timeout for potentially longer responses
        response = model.generate_content(build_prompt(topic, include_code, requirements), request_options={"timeout": 90})
        text = response.text.strip()
        # print(f"\n📄 Full Gemini Output (for debugging):\n---\n{text}\n---\n") # Uncomment to see raw output


        data = parse_assignment_response(text, include_code)

        # ====== Create DOCX ======
        doc = Document()

        # Apply default style formatting (Times New Roman, 12pt, 1.5 spacing)
        styles = doc.styles
        style_normal = styles['Normal']
        font = style_normal.font
        font.name = 'Times New Roman'
        font.size = Pt(12)
        para_format = style_normal.paragraph_format
        para_format.line_spacing = 1.5
        para_format.space_before = Pt(0)
        para_format.space_after = Pt(0)

        # Note: Adding page borders is not directly supported by python-docx.
        # This feature would require more complex manipulation of the document's XML.
        print("ℹ️ Note: Adding page borders is not supported by the current library.")


        # Main Heading (Assignment - n)
        main_heading_part1 = f"Assignment - {assignment_number}"
        add_paragraph(doc, main_heading_part1, size=18, bold=True, align_center=True, spacing=1.0, color=HEADING_COLOR)

        # Assignment Title (Below Assignment - n)
        assignment_title_text = f"({data['title']})"
        add_paragraph(doc, assignment_title_text, size=16, bold=True, align_center=True, spacing=1.0, color=HEADING_COLOR) # Slightly smaller, bold


        # Aim - Light Blue Heading
        add_paragraph(doc, "\nAim:", bold=True, spacing=1.0, color=LIGHT_BLUE)
        add_paragraph(doc, data["aim"], spacing=1.5)


        # Theory - Light Blue Heading, Structured with possible Bullet Points
        add_paragraph(doc, "\nTheory:", bold=True, spacing=1.0, color=LIGHT_BLUE)
        theory_lines = data["theory"].split('\n') # Split by single newline to process potential lists
        for line in theory_lines:
            line = line.strip()
            if not line:
                doc.add_paragraph('', style='Normal') # Add blank line for paragraph separation
                continue
            # Check for bullet point markers (* or -)
            if line.startswith('* ') or line.startswith('- '):
                add_list_item(doc, line, style='List Bullet', size=12, font="Times New Roman", spacing=1.5)
            else:
                 # Add as regular paragraph if not a list item
                 add_paragraph(doc, line, spacing=1.5)


        # Code - Light Blue Heading, Monospace font
        if include_code and data["code"]:
            add_paragraph(doc, "\nCode:", bold=True, spacing=1.0, color=LIGHT_BLUE)
            for line in data["code"].splitlines():
                add_paragraph(doc, line, size=11, spacing=1.0, font="Consolas")


        # Output - Light Blue Heading, Monospace font
        if include_code and data["output"]:
            add_paragraph(doc, "\nOutput:", bold=True, spacing=1.0, color=LIGHT_BLUE)
            for line in data["output"].splitlines():
                add_paragraph(doc, line, size=11, spacing=1.0, font="Consolas")


        # Conclusion - Light Blue Heading, Concise content
        add_paragraph(doc, "\nConclusion:", bold=True, spacing=1.0, color=LIGHT_BLUE)
        for paragraph_text in data["conclusion"].split('\n\n'):
            add_paragraph(doc, paragraph_text.strip(), spacing=1.5)

        # Add the user-provided LO Mapping below Gemini's conclusion - Light Blue Heading for LO Mapping
        if lo_mapping_text:
            add_paragraph(doc, "\nLO Mapping:", bold=True, spacing=1.0, color=LIGHT_BLUE)
            # Add the user's LO mapping text as a regular paragraph
            add_paragraph(doc, lo_mapping_text.strip(), spacing=1.5)


        # Save DOCX
        # Make filename safer by removing characters other than letters, numbers, _, -
        safe_topic = "".join(c for c in topic if c.isalnum() or c in (' ', '_', '-')).rstrip()
        safe_topic = safe_topic.replace(' ', '_')
        if not safe_topic: safe_topic = "Assignment" # Fallback if topic was empty or invalid chars
        filename = f"Assignment_{safe_topic}.docx"


        doc.save(filename)
        print(f"\n✅ Assignment saved as: {filename}")

        # --- Open the saved file ---
        print(f"🚀 Attempting to open '{filename}'...")
        try:
            if os.name == "nt": # Windows
                os.startfile(filename)
            elif sys.platform == "darwin": # macOS
                subprocess.run(["open", filename], check=True)
            elif os.name == "posix": # Linux/Unix
                # Check if xdg-open is available
                if os.system("command -v xdg-open > /dev/null") == 0:
                    subprocess.run(["xdg-open", filename], check=True)
                else:
                    print("ℹ️ 'xdg-open' command not found. Could not automatically open the document. Please open it manually.")
            else:
                print("ℹ️ Could not automatically open the document. Please open it manually.")
        except FileNotFoundError:
            print(f"⚠️ Error: Command to open file not found.")
        except subprocess.CalledProcessError as e:
            print(f"⚠️ Error opening document: {e}")
        except Exception as e:
            print(f"⚠️ An unexpected error occurred while trying to open the document: {e}")


    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")
        print("❌ Failed to generate or save assignment.")

# --- Explanation for Optional Input ---
def explain_optional_requirements_input():
    print("\n--- Explanation: Specific Requirements/Constraints Input ---")
    print("The prompt asking '📝 Enter any specific requirements or constraints for the assignment (optional):' is where you can provide extra details to help Gemini generate a more tailored assignment.")
    print("Think of this as giving the AI additional instructions that aren't covered by the basic 'Topic' or 'Include Code' questions.")
    print("\nExamples of what you could enter here:")
    print("- 'The code must be written in Python 3.8 and use only built-in libraries.'")
    print("- 'The Theory section should include a brief history of the topic.'")
    print("- 'The assignment should analyze a dataset from a CSV file (assume the file is available).' (Note: Gemini will simulate this analysis unless you provide data.)")
    print("- 'Focus the Code section on demonstrating object-oriented programming principles.'")
    print("- 'Limit the Theory section to no more than two pages.'")
    print("- 'Include a sub-section in the Theory about security considerations.'")
    print("\nProviding clear constraints and specific details here will help Gemini understand exactly what you need and generate content that is more accurate and relevant to your specific assignment requirements.")
    print("If you have no additional requirements, you can just press Enter to leave it blank.")

# To show this explanation to the user, you could add a call to this function
# somewhere after the main execution, e.g., outside the if __name__ == "__main__": block
# or within it after the main process. For now, it's defined as a separate function.